export interface RegistryComponent {
  name: string
  description: string
  category: ComponentCategory
  dependencies: string[]
  radixDeps: string[]
  files: string[]
  variants?: string[]
  tags?: string[]
}

export type ComponentCategory =
  | "layout"
  | "inputs"
  | "navigation"
  | "feedback"
  | "data-display"
  | "ai"
  | "wow"

export const REGISTRY: RegistryComponent[] = [
  // ─── Layout ───────────────────────────────────────────────
  {
    name: "card",
    description: "A flexible card container with multiple variants",
    category: "layout",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/layout/card.tsx"],
    variants: ["default", "glass", "glow", "gradient", "outlined", "elevated"],
    tags: ["container", "layout"],
  },
  {
    name: "badge",
    description: "A small status indicator component",
    category: "layout",
    dependencies: [],
    radixDeps: [],
    files: ["components/layout/badge.tsx"],
    tags: ["status", "label"],
  },
  {
    name: "avatar",
    description: "An image element with a fallback for representing the user",
    category: "layout",
    dependencies: [],
    radixDeps: ["@radix-ui/react-avatar"],
    files: ["components/layout/avatar.tsx"],
    tags: ["user", "image"],
  },
  {
    name: "separator",
    description: "A visual separator between content sections",
    category: "layout",
    dependencies: [],
    radixDeps: ["@radix-ui/react-separator"],
    files: ["components/layout/separator.tsx"],
    tags: ["divider", "layout"],
  },
  {
    name: "scroll-area",
    description: "A scrollable container with custom scrollbars",
    category: "layout",
    dependencies: [],
    radixDeps: ["@radix-ui/react-scroll-area"],
    files: ["components/layout/scroll-area.tsx"],
    tags: ["scroll", "container"],
  },
  {
    name: "collapsible",
    description: "A collapsible container for showing/hiding content",
    category: "layout",
    dependencies: [],
    radixDeps: ["@radix-ui/react-collapsible"],
    files: ["components/layout/collapsible.tsx"],
    tags: ["toggle", "container"],
  },
  {
    name: "resizable",
    description: "Resizable panel groups for split-pane layouts",
    category: "layout",
    dependencies: ["react-resizable-panels"],
    radixDeps: [],
    files: ["components/layout/resizable.tsx"],
    tags: ["layout", "panel", "resizable"],
  },
  {
    name: "tag",
    description: "Tags and chip components, including a tag input",
    category: "layout",
    dependencies: [],
    radixDeps: [],
    files: ["components/layout/tag.tsx"],
    variants: ["default", "secondary", "outline", "success", "warning", "destructive", "info"],
    tags: ["chip", "label", "input"],
  },
  // ─── Inputs ───────────────────────────────────────────────
  {
    name: "button",
    description: "A button component with multiple variants and states",
    category: "inputs",
    dependencies: ["framer-motion"],
    radixDeps: ["@radix-ui/react-slot"],
    files: ["components/inputs/button.tsx"],
    variants: ["default", "destructive", "outline", "secondary", "ghost", "link", "glow", "glass", "gradient"],
    tags: ["action", "interactive"],
  },
  {
    name: "input",
    description: "A text input component with multiple variants",
    category: "inputs",
    dependencies: [],
    radixDeps: [],
    files: ["components/inputs/input.tsx"],
    tags: ["form", "text"],
  },
  {
    name: "textarea",
    description: "A multi-line text input component",
    category: "inputs",
    dependencies: [],
    radixDeps: [],
    files: ["components/inputs/textarea.tsx"],
    tags: ["form", "text"],
  },
  {
    name: "label",
    description: "A label component for form elements",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-label"],
    files: ["components/inputs/label.tsx"],
    tags: ["form"],
  },
  {
    name: "checkbox",
    description: "A checkbox with label and description support",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-checkbox"],
    files: ["components/inputs/checkbox.tsx"],
    tags: ["form", "selection"],
  },
  {
    name: "switch",
    description: "A toggle switch with label and description",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-switch"],
    files: ["components/inputs/switch.tsx"],
    tags: ["form", "toggle"],
  },
  {
    name: "radio-group",
    description: "A radio button group for single selection",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-radio-group"],
    files: ["components/inputs/radio-group.tsx"],
    tags: ["form", "selection"],
  },
  {
    name: "select",
    description: "A dropdown select component",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-select"],
    files: ["components/inputs/select.tsx"],
    tags: ["form", "dropdown"],
  },
  {
    name: "slider",
    description: "A range slider component",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-slider"],
    files: ["components/inputs/slider.tsx"],
    tags: ["form", "range"],
  },
  {
    name: "toggle",
    description: "Toggle button and toggle group components",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-toggle", "@radix-ui/react-toggle-group"],
    files: ["components/inputs/toggle.tsx"],
    tags: ["form", "selection"],
  },
  {
    name: "rating",
    description: "A star rating component with hover effects",
    category: "inputs",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/inputs/rating.tsx"],
    tags: ["form", "rating", "stars"],
  },
  {
    name: "otp-input",
    description: "A one-time password input with slot groups",
    category: "inputs",
    dependencies: ["input-otp"],
    radixDeps: [],
    files: ["components/inputs/otp-input.tsx"],
    tags: ["form", "otp", "verification"],
  },
  {
    name: "calendar",
    description: "A date picker calendar component",
    category: "inputs",
    dependencies: ["react-day-picker", "date-fns"],
    radixDeps: [],
    files: ["components/inputs/calendar.tsx"],
    tags: ["date", "form"],
  },
  {
    name: "date-picker",
    description: "Date and date range picker with calendar popover",
    category: "inputs",
    dependencies: ["react-day-picker", "date-fns"],
    radixDeps: ["@radix-ui/react-popover"],
    files: ["components/inputs/date-picker.tsx", "components/inputs/calendar.tsx", "components/navigation/popover.tsx"],
    tags: ["date", "form", "picker"],
  },
  {
    name: "combobox",
    description: "A searchable select with single and multi-select modes",
    category: "inputs",
    dependencies: [],
    radixDeps: ["@radix-ui/react-popover"],
    files: ["components/inputs/combobox.tsx", "components/navigation/popover.tsx"],
    tags: ["form", "search", "select"],
  },
  {
    name: "form",
    description: "React Hook Form integration with validation",
    category: "inputs",
    dependencies: ["react-hook-form"],
    radixDeps: ["@radix-ui/react-label", "@radix-ui/react-slot"],
    files: ["components/inputs/form.tsx"],
    tags: ["form", "validation"],
  },
  // ─── Navigation ───────────────────────────────────────────
  {
    name: "tabs",
    description: "A tabbed navigation component",
    category: "navigation",
    dependencies: ["framer-motion"],
    radixDeps: ["@radix-ui/react-tabs"],
    files: ["components/navigation/tabs.tsx"],
    variants: ["default", "pills", "underline", "boxed"],
    tags: ["navigation"],
  },
  {
    name: "command",
    description: "A command palette for searching and executing commands",
    category: "navigation",
    dependencies: ["cmdk"],
    radixDeps: [],
    files: ["components/navigation/command.tsx"],
    tags: ["search", "navigation"],
  },
  {
    name: "dropdown-menu",
    description: "A dropdown menu with submenus, checkboxes, and radio items",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-dropdown-menu"],
    files: ["components/navigation/dropdown-menu.tsx"],
    tags: ["menu", "navigation"],
  },
  {
    name: "tooltip",
    description: "A tooltip with SimpleTooltip convenience wrapper",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-tooltip"],
    files: ["components/navigation/tooltip.tsx"],
    tags: ["overlay", "info"],
  },
  {
    name: "popover",
    description: "A floating popover container",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-popover"],
    files: ["components/navigation/popover.tsx"],
    tags: ["overlay", "floating"],
  },
  {
    name: "breadcrumb",
    description: "Breadcrumb navigation with ellipsis support",
    category: "navigation",
    dependencies: [],
    radixDeps: [],
    files: ["components/navigation/breadcrumb.tsx"],
    tags: ["navigation", "path"],
  },
  {
    name: "pagination",
    description: "Pagination navigation for multi-page content",
    category: "navigation",
    dependencies: [],
    radixDeps: [],
    files: ["components/navigation/pagination.tsx"],
    tags: ["navigation", "pages"],
  },
  {
    name: "sheet",
    description: "A slide-in sheet/sidebar from any edge",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-dialog"],
    files: ["components/navigation/sheet.tsx"],
    variants: ["top", "bottom", "left", "right"],
    tags: ["overlay", "sidebar"],
  },
  {
    name: "hover-card",
    description: "A card that appears on hover",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-hover-card"],
    files: ["components/navigation/hover-card.tsx"],
    tags: ["overlay", "preview"],
  },
  {
    name: "stepper",
    description: "A step-by-step progress component",
    category: "navigation",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/navigation/stepper.tsx"],
    tags: ["progress", "wizard"],
  },
  {
    name: "context-menu",
    description: "A right-click context menu",
    category: "navigation",
    dependencies: [],
    radixDeps: ["@radix-ui/react-context-menu"],
    files: ["components/navigation/context-menu.tsx"],
    tags: ["menu", "right-click"],
  },
  {
    name: "drawer",
    description: "A bottom drawer component (powered by Vaul)",
    category: "navigation",
    dependencies: ["vaul"],
    radixDeps: [],
    files: ["components/navigation/drawer.tsx"],
    tags: ["overlay", "mobile", "bottom-sheet"],
  },
  {
    name: "carousel",
    description: "A touch-friendly carousel / slider",
    category: "navigation",
    dependencies: ["embla-carousel-react"],
    radixDeps: [],
    files: ["components/navigation/carousel.tsx"],
    tags: ["slider", "gallery"],
  },
  // ─── Feedback ─────────────────────────────────────────────
  {
    name: "dialog",
    description: "A modal dialog component",
    category: "feedback",
    dependencies: ["framer-motion"],
    radixDeps: ["@radix-ui/react-dialog"],
    files: ["components/feedback/dialog.tsx"],
    tags: ["modal", "overlay"],
  },
  {
    name: "toast",
    description: "A toast notification component (powered by Sonner)",
    category: "feedback",
    dependencies: ["sonner"],
    radixDeps: [],
    files: ["components/feedback/toast.tsx"],
    tags: ["notification", "feedback"],
  },
  {
    name: "skeleton",
    description: "Loading skeleton placeholder components",
    category: "feedback",
    dependencies: [],
    radixDeps: [],
    files: ["components/feedback/skeleton.tsx"],
    tags: ["loading", "placeholder"],
  },
  {
    name: "progress",
    description: "A progress bar component",
    category: "feedback",
    dependencies: ["framer-motion"],
    radixDeps: ["@radix-ui/react-progress"],
    files: ["components/feedback/progress.tsx"],
    tags: ["loading", "status"],
  },
  {
    name: "accordion",
    description: "An expandable accordion component",
    category: "feedback",
    dependencies: [],
    radixDeps: ["@radix-ui/react-accordion"],
    files: ["components/feedback/accordion.tsx"],
    tags: ["collapse", "faq"],
  },
  {
    name: "alert",
    description: "Alert messages with 5 variants and dismissible support",
    category: "feedback",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/feedback/alert.tsx"],
    variants: ["default", "info", "success", "warning", "destructive"],
    tags: ["notification", "message"],
  },
  {
    name: "alert-dialog",
    description: "A confirmation dialog with action and cancel buttons",
    category: "feedback",
    dependencies: [],
    radixDeps: ["@radix-ui/react-alert-dialog"],
    files: ["components/feedback/alert-dialog.tsx"],
    tags: ["modal", "confirm"],
  },
  {
    name: "spinner",
    description: "Loading spinners: Spinner, LoadingOverlay, DotsSpinner",
    category: "feedback",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/feedback/spinner.tsx"],
    tags: ["loading", "indicator"],
  },
  // ─── Data Display ─────────────────────────────────────────
  {
    name: "code-block",
    description: "A syntax-highlighted code display component",
    category: "data-display",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/data-display/code-block.tsx"],
    tags: ["code", "syntax"],
  },
  {
    name: "table",
    description: "HTML table primitives with styled components",
    category: "data-display",
    dependencies: [],
    radixDeps: [],
    files: ["components/data-display/table.tsx"],
    tags: ["table", "data"],
  },
  {
    name: "data-table",
    description: "Feature-rich data table powered by TanStack Table",
    category: "data-display",
    dependencies: ["@tanstack/react-table"],
    radixDeps: [],
    files: ["components/data-display/data-table.tsx", "components/data-display/table.tsx"],
    tags: ["table", "data", "sort", "filter", "pagination"],
  },
  {
    name: "chart",
    description: "Charts: Line, Bar, Area, Pie/Donut, Radar (powered by Recharts)",
    category: "data-display",
    dependencies: ["recharts"],
    radixDeps: [],
    files: ["components/data-display/chart.tsx"],
    variants: ["line", "bar", "area", "pie", "donut", "radar"],
    tags: ["chart", "graph", "visualization"],
  },
  {
    name: "timeline",
    description: "A vertical timeline with animated items",
    category: "data-display",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/data-display/timeline.tsx"],
    tags: ["timeline", "history"],
  },
  {
    name: "statistic",
    description: "Animated numeric statistic display with trend indicators",
    category: "data-display",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/data-display/statistic.tsx"],
    tags: ["number", "metric", "kpi"],
  },
  {
    name: "empty",
    description: "Empty state placeholder component",
    category: "data-display",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/data-display/empty.tsx"],
    tags: ["empty", "placeholder", "state"],
  },
  // ─── AI ───────────────────────────────────────────────────
  {
    name: "chat-ui",
    description: "A complete AI chat interface component",
    category: "ai",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/ai/chat-ui.tsx"],
    tags: ["ai", "chat"],
  },
  // ─── WOW ──────────────────────────────────────────────────
  {
    name: "aurora-background",
    description: "An animated aurora borealis background effect",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/aurora-background.tsx"],
    tags: ["background", "animation"],
  },
  {
    name: "meteors",
    description: "Animated meteor shower effect",
    category: "wow",
    dependencies: [],
    radixDeps: [],
    files: ["components/wow/meteors.tsx"],
    tags: ["animation", "particles"],
  },
  {
    name: "magic-card",
    description: "A card with mouse-following gradient effect",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/magic-card.tsx"],
    tags: ["card", "animation", "mouse"],
  },
  {
    name: "spotlight",
    description: "Spotlight hover effect and text",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/spotlight.tsx"],
    tags: ["animation", "hover"],
  },
  {
    name: "marquee",
    description: "Infinite scrolling marquee component",
    category: "wow",
    dependencies: [],
    radixDeps: [],
    files: ["components/wow/marquee.tsx"],
    tags: ["animation", "scroll"],
  },
  {
    name: "animated-beam",
    description: "Animated connection beam between elements",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/animated-beam.tsx"],
    tags: ["animation", "svg"],
  },
  {
    name: "animated-text",
    description: "Text with entrance animations (word-by-word, typing, etc.)",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/animated-text.tsx"],
    tags: ["text", "animation"],
  },
  {
    name: "border-beam",
    description: "Animated border beam effect",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/glowing-border.tsx"],
    tags: ["border", "animation"],
  },
  {
    name: "particle-system",
    description: "Interactive particle system with canvas",
    category: "wow",
    dependencies: [],
    radixDeps: [],
    files: ["components/wow/particle-system.tsx"],
    tags: ["canvas", "particles", "interactive"],
  },
  {
    name: "bento-grid",
    description: "Bento-style grid layout with animated cards",
    category: "wow",
    dependencies: ["framer-motion"],
    radixDeps: [],
    files: ["components/wow/bento-grid.tsx"],
    tags: ["layout", "grid"],
  },
]

export function getComponent(name: string): RegistryComponent | undefined {
  return REGISTRY.find((c) => c.name === name)
}

export function getComponentsByCategory(category: ComponentCategory): RegistryComponent[] {
  return REGISTRY.filter((c) => c.category === category)
}

export function searchComponents(query: string): RegistryComponent[] {
  const q = query.toLowerCase()
  return REGISTRY.filter(
    (c) =>
      c.name.includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.tags?.some((t) => t.includes(q)),
  )
}
